cat <<EOF > aws-auth.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::239076167106:role/eks-ec2
      username: jenkins
      groups:
        - system:masters
EOF
